apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flex-bigquery-soda-alerts
  namespace: flex
  labels:
    team: flex
spec:
  groups:
    - name: flex-bigquery-soda-alerts
      rules:
        - alert: NaisjobFailed
          expr: kube_job_failed{job_name=~"^flex-bigquery-soda.*", namespace="flex"} > 0
          for: 3m
          annotations:
            consequence: "Naisjob som kjører Soda-sjekker feilet."
            action: "@flexmembers - Sjekk https://logs.adeo.no/app/r/s/Cush4"
            summary: |-
              Naisjob som kjører Soda-sjekker for Team Flex feilet.
              Repo: https://github.com/navikt/flex-bigquery-soda
              Alert: https://github.com/navikt/navikt/flex-bigquery-soda/blob/main/nais/alerts.yaml
          labels:
            namespace: flex
            severity: warning
            flex-bigquery-soda-matcher: prod-alert
            alert_type: custom

---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: flex-dev-slack-alert
  namespace: flex
  labels:
    team: flex
    alertmanagerConfig: flex-dev-slack-alert
spec:
  receivers:
    - name: flex-bigquery-soda-alerts-slack-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#flex-dev'
          iconEmoji: ':alert:'
          username: 'Alert prod-gcp'
          sendResolved: true
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts }}
            {{ if or .Annotations.summary .Annotations.message }}
            {{ or .Annotations.summary .Annotations.message }}
            {{ println " " }}
            {{- end }}
            {{- if .Annotations.action }}
            • *action*: {{ .Annotations.action }} {{ println " " }}
            {{- end }}
            {{ end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "flex-bigquery-soda-alerts-matcher"
        matchType: "="
        value: "prod-alert"
    groupInterval: 10s
    groupWait: 5s
    receiver: flex-bigquery-soda-alerts-slack-receiver
    repeatInterval: 25h