apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: flex
  name: flex-bigquery-soda{{#if cron.schedule}}{{else}}-run-on-deploy{{/if}}
  namespace: flex
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/nada/nada-soda:2024.07.15-10.50-6a62e42
  accessPolicy:
    outbound:
      rules:
        - application: nada-soda
          namespace: nada
  env:
    - name: SODA_CONFIG
      value: /var/run/configmaps/soda-config/config.yaml
    - name: SODA_CHECKS_FOLDER
      value: /var/run/configmaps/soda-checks
    - name: SLACK_CHANNEL
      value: "{{ slack.channel }}"
    - name: NOTIFY_OK_SCAN_STATUS
      value: "true"
  {{#if cron.schedule}}
  schedule: {{ cron.schedule }}
  {{/if}}
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  backoffLimit: 1
  concurrencyPolicy: Forbid
  filesFrom:
    - configmap: soda-checks
    - configmap: soda-config
  gcp:
    permissions:
    - resource:
        apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
        kind: Project
        name: {{ gcp.project_id }}
      role: roles/bigquery.readSessionUser
    - resource:
        apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
        kind: Project
        name: {{ gcp.project_id }}
      role: roles/bigquery.dataViewer
    - resource:
        apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
        kind: Project
        name: {{ gcp.project_id }}
      role: roles/bigquery.jobUser
    - resource:
        apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
        kind: Project
        name: {{ gcp.project_id }}
      role: roles/bigquery.connectionUser
