apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: flex
data:
  flex_dataset.yaml: |
    checks for soda-sendt-sykepengesoknad-avstemming-view:
      - row_count = 0:
          name: "Det finnes sykepengesøknader med status SENDT som ikke finnes i sykepengesoknad-arkivering-oppgave"
    checks for soda-spinnsyn-datastream-view:
      - row_count = 0:
          name: "Det er data i spinnsyn-backend.vedtak_v2 som ikke er streamet til BigQuery"
    checks for soda-sykepengesoknad-datastream-view:
      - row_count = 0:
          name: "Det er data i sykepengesoknad-backend.soknader som ikke er streamet til BigQuery"
    checks for soda-modia-kontakt-metrikk-datastream-view:
      - row_count = 0:
          name: "Det er data i modia-kontakt-metrikk.henvendelse som ikke er streamet til BigQuery"
    checks for soda-sak-status-metrikk-datastream-view:
      - row_count = 0:
          name: "Det er data i sak-status-metrikk.vedtaksperiode_tilstand som ikke er streamet til BigQuery"
    checks for soda-flexjar-datastream-view:
      - row_count = 0:
          name: "Det er data i flexjar-backend.feedback som ikke er streamet til BigQuery"
    checks for soda-arkivering-oppgave-datastream-view:
      - row_count = 0:
          name: "Det er data i sykepengesoknad-arkivering-oppgave.oppgavestyring som ikke er streamet til BigQuery"

  sykepengesoknad_datastream.yaml: |
    checks for public_sykepengesoknad:
      - freshness(opprettet) < 12h:
          name: "Det er ikke streamet data fra sykepengesoknad-backend til til BigQuery siste 12 timer"

  spinnsyn_datastream.yaml: |
    checks for public_vedtak_v2:
      - freshness(opprettet) < 12h:
          name: "Det er ikke streamet data fra spinnsyn-backend til til BigQuery siste 12 timer"

  arkivering_oppgave_datastream.yaml: |
    checks for public_oppgavestyring:
      - freshness(opprettet) < 12h:
          name: "Det er ikke streamet data fra sykepengesoknad-arkivering-oppgave til til BigQuery siste 12 timer"

  sak_status_metrikk_datastream.yaml: |
    checks for public_vedtaksperiode_tilstand:
      - freshness(tidspunkt) < 12h:
          name: "Det er ikke streamet data fra sykepengesoknad-sak-status-metrikk til til BigQuery siste 12 timer"

  modia_kontakt_metrikk_datastream.yaml: |
    checks for public_henvendelse:
      - freshness(tidspunkt) < 12h:
          name: "Det er ikke streamet data fra modia-kontakt-metrikk til til BigQuery siste 12 timer"

  flexjar_datastream.yaml: |
    checks for public_feedback:
      - freshness(opprettet) < 24h:
          name: "Det er ikke streamet data fra flexjar-backend til til BigQuery siste 24 timer"