apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: flex
data:
  soda_dataset.yaml: |
    checks for sendt-sykepengesoknad-arkivering-oppgave-avstemming:
      - row_count = 0:
          name: "Det finnes sykepengesøknader med status SENDT som ikke finnes i sykepengesoknad-arkivering-oppgave."

    checks for spinnsyn-vedtak-datastream-avstemming:
      - row_count = 0:
          name: "Det finnes data i spinnsyn-backend.vedtak_v2 som ikke er streamet til BigQuery."

    checks for sykepengesoknad-sykepengesoknad-avstemming:
      - row_count = 0:
          name: "Det finnes data i sykepengesoknad-backend.soknader som ikke er streamet til BigQuery."

    checks for arkivering-oppgave-oppgavestyring-avstemming:
      - row_count = 0:
          name: "Det finnes data i modia-kontakt-metrikk.henvendelse som ikke er streamet til BigQuery."

    checks for sak-status-metrikk-vedtaksperiode-avstemming:
      - row_count = 0:
          name: "Det finnes data i sak-status-metrikk.vedtaksperiode_tilstand som ikke er streamet til BigQuery."

    checks for modia-kontakt-metrikk-henvendelse-avstemming:
      - row_count = 0:
          name: "Det finnes data i sykepengesoknad-arkivering-oppgave.oppgavestyring som ikke er streamet til BigQuery."

    checks for flexjar-feedback-avstemming:
      - row_count = 0:
          name: "Det finnes data i flexjar-backend.feedback som ikke er streamet til BigQuery."

    checks for flex-inntektsmelding-status-avstemming:
      - row_count = 0:
          name: "Det finnes data i flex-inntektsmelding-status.vedtaksperiode som ikke er streamet til BigQuery."

    checks for manglende-inntektsmelding-morgendagens-prognose:
      - row_count < 500:
          name: "Det er flere enn 500 planlagte varsler om manglende inntektsmelding i morgen."

  sykepengesoknad_datastream.yaml: |
    checks for public_sykepengesoknad:
      - freshness(opprettet) < 24h:
          name: "Det er ikke streamet data fra sykepengesoknad-backend til til BigQuery siste 24 timer."

  spinnsyn_datastream.yaml: |
    checks for public_vedtak_v2:
      - freshness(opprettet) < 24h:
          name: "Det er ikke streamet data fra spinnsyn-backend til til BigQuery siste 24 timer."

  arkivering_oppgave_datastream.yaml: |
    checks for public_oppgavestyring:
      - freshness(opprettet) < 24h:
          name: "Det er ikke streamet data fra sykepengesoknad-arkivering-oppgave til til BigQuery siste 24 timer."

  sak_status_metrikk_datastream.yaml: |
    checks for public_vedtaksperiode_tilstand:
      - freshness(tidspunkt) < 24h:
          name: "Det er ikke streamet data fra sykepengesoknad-sak-status-metrikk til til BigQuery siste 24 timer."

  modia_kontakt_metrikk_datastream.yaml: |
    checks for public_henvendelse:
      - freshness(tidspunkt) < 24h:
          name: "Det er ikke streamet data fra modia-kontakt-metrikk til til BigQuery siste 24 timer."

  flexjar_datastream.yaml: |
    checks for public_feedback:
      - freshness(opprettet) < 24h:
          name: "Det er ikke streamet data fra flexjar-backend til til BigQuery siste 24 timer."

  flex_inntektsmelding_status_datastream.yaml: |
    checks for public_vedtaksperiode:
      - freshness(opprettet) < 24h:
          name: "Det er ikke streamet data fra flex-inntektsmelding-status til til BigQuery siste 24 timer."