apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-config
  namespace: flex
data:
  config.yaml: |
    data_source flex_dataset:
      type: bigquery
      connection:
        project_id: {{ gcp.project_id }}
        dataset: flex_dataset
    data_source sykepengesoknad_datastream:
      type: bigquery
      connection:
        project_id: {{ gcp.project_id }}
        dataset: sykepengesoknad_datastream

