apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-config
  namespace: flex
data:
  config.yaml: |
    data_source flex_dataset:
      type: bigquery
      connection:
        project_id: {{ gcp.project_id }}
        dataset: flex_dataset
    data_source sykepengesoknad_datastream:
      type: bigquery
      connection:
        project_id: {{ gcp.project_id }}
        dataset: sykepengesoknad_datastream
    data_source spinnsyn_datastream:
      type: bigquery
      connection:
        project_id: {{ gcp.project_id }}
        dataset: spinnsyn_datastream
    data_source arkivering_oppgave_datastream:
      type: bigquery
      connection:
        project_id: {{ gcp.project_id }}
        dataset: arkivering_oppgave_datastream
    data_source sak_status_metrikk_datastream:
      type: bigquery
      connection:
        project_id: {{ gcp.project_id }}
        dataset: sak_status_metrikk_datastream
    

