apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-config
  namespace: flex
data:
  config.yaml: |
    data_source soda_dataset:
      type: bigquery
      connection:
        project_id: {{ gcp.project_id }}
        dataset: soda_dataset
    data_source sykepengesoknad_datastream:
      type: bigquery
      connection:
        project_id: {{ gcp.project_id }}
        dataset: sykepengesoknad_datastream
    data_source spinnsyn_datastream:
      type: bigquery
      connection:
        project_id: {{ gcp.project_id }}
        dataset: spinnsyn_datastream
    data_source arkivering_oppgave_datastream:
      type: bigquery
      connection:
        project_id: {{ gcp.project_id }}
        dataset: arkivering_oppgave_datastream
    data_source flexjar_datastream:
      type: bigquery
      connection:
        project_id: {{ gcp.project_id }}
        dataset: flexjar_datastream
    data_source inntektsmelding_status_datastream:
      type: bigquery
      connection:
        project_id: {{ gcp.project_id }}
        dataset: inntektsmelding_status_datastream


