apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: flex
data:
  soda_dataset.yaml: |
    checks for sendt_sykepengesoknad_arkivering_oppgave_avstemming:
      - row_count = 0:
          name: "Det finnes sykepengesøknader med status SENDT som ikke finnes i sykepengesoknad-arkivering-oppgave."

    checks for spinnsyn_vedtak_datastream_avstemming:
      - row_count = 0:
          name: "Det finnes data i spinnsyn-backend.vedtak_v2 som ikke er streamet til BigQuery."

    checks for sykepengesoknad_sykepengesoknad_avstemming:
      - row_count = 0:
          name: "Det finnes data i sykepengesoknad-backend.soknader som ikke er streamet til BigQuery."

    checks for arkivering_oppgave_oppgavestyring_avstemming:
      - row_count = 0:
          name: "Det finnes data i sykepengesoknad-arkivering-oppgave.oppgavestyring som ikke er streamet til BigQuery."

    checks for flexjar_feedback_avstemming:
      - row_count = 0:
          name: "Det finnes data i flexjar-backend.feedback som ikke er streamet til BigQuery."

    checks for arkivering_oppgave_venter_pa_bomlo:
      - row_count <= 25:
          name: "Det er fler enn 25 oppgaver i sykepengesoknad-arkivering-oppgave.oppgavestyring som venter på signal fra Bømlo."

    checks for forsinket_saksbehandling_varslinger_sendt_nylig:
      - row_count = 4:
          name: "Det er varseltyper som ikke er sendt ut nylig fra flex-inntektsmelding-status."
    
    checks for flex_inntektsmelding_status_datastream_avstemming:
      - row_count = 0:
          name: "Det finnes data i flex-inntektsmelding-status.vedtaksperiode_behandling_status som ikke er streamet til BigQuery."

    checks for spinnsyn_utbetaling_spinnsyn_arkivering_avstemming: 
      - row_count = 0: 
          name: "Det finnes utbetalinger i spinnsyn-utbetaling som ikke finnes som vedtak i spinnsyn-arkivering." 
   
    checks for frisk_til_arbeid_vedtak_overlapp:
      - row_count = 0:
          name: "Det finnes FriskTilArbeid vedtak som overlapper med tidligere vedtak."

    checks for frisk_til_arbeid_vedtak_arbeidssokerperiode:
      - row_count = 0:
          name: "Det finnes FriskTilArbeid hvor bruker ikke er registert i arbeidsøkerregisteret."

    checks for frisk_til_arbeid_vedtak_ubehandlet:
      - row_count = 0:
          name: "Det finnes FriskTilArbeid vedtak som har hatt status NY lengre enn 24 timer."
          
    checks for flex_inntektsmelding_status_forelagte_opplysninger_forsinket:
      - row_count = 0:
          name: "Noen forelagte opplysninger er forsinket, dette må sjekkes manuelt."
      
    checks for sykmeldinghendelser_korrelerer_med_tsm:
      - row_count = 0:
          name: "Det finnes sykmeldinghendelser som ikke er korrelert med TSM."
          
    checks for sykepengesoknad_aktivering_forsinket:
      - row_count = 0:
          name: "Det finnes sykepengesøknader som burde vært aktivert"

  sykepengesoknad_datastream.yaml: |
    checks for public_sykepengesoknad:
      - freshness(opprettet) < 24h:
          name: "Det er ikke streamet data fra sykepengesoknad-backend til til BigQuery siste 24 timer."

  flex_sykmeldinger_backend_datastream.yaml: |
    checks for public_sykmelding:
      - freshness(opprettet) < 24h:
          name: "Det er ikke streamet data fra flex-sykmeldinger-backend til til BigQuery siste 24 timer."

  spinnsyn_datastream.yaml: |
    checks for public_vedtak_v2:
      - freshness(opprettet) < 24h:
          name: "Det er ikke streamet data fra spinnsyn-backend til til BigQuery siste 24 timer."

  arkivering_oppgave_datastream.yaml: |
    checks for public_oppgavestyring:
      - freshness(opprettet) < 24h:
          name: "Det er ikke streamet data fra sykepengesoknad-arkivering-oppgave til til BigQuery siste 24 timer."

  flexjar_datastream.yaml: |
    checks for public_feedback:
      - freshness(opprettet) < 24h:
          name: "Det er ikke streamet data fra flexjar-backend til til BigQuery siste 24 timer."

  spinnsyn_arkivering_datastream.yaml: |
    checks for public_arkivert_vedtak:
      - freshness(opprettet) < 24h:
          name: "Det er ikke streamet data fra spinnsyn-arkivering til til BigQuery siste 24 timer."

