apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: flex
data:
  flex_dataset.yaml: |
    checks for soda-sendt-sykepengesoknad-avstemming:
      - row_count = 0:
          name: "Det skal ikke finnes søknader med status SENDT som ikke finnes i sykepengesoknad-arkivering-oppgave."

  sykepengesoknad_datastream.yaml: |
    checks for public_sykepengesoknad:
      - freshness(opprettet) < 12h:
          name: "Det er ikke streamet sykepengesøknader til BigQuery siste 12 timer"

  spinnsyn_datastream.yaml: |
    checks for public_vedtak_v2:
      - freshness(opprettet) < 12h:
          name: "Det er ikke streamet vedtak til BigQuery siste 12 timer"
