data_source soda_dataset:
  type: bigquery
  connection:
    project_id: flex-prod-af40
    dataset: soda_dataset

data_source sykepengesoknad_datastream:
  type: bigquery
  connection:
    project_id: flex-prod-af40
    dataset: sykepengesoknad_datastream

data_source spinnsyn_datastream:
  type: bigquery
  connection:
    project_id: flex-prod-af40
    dataset: spinnsyn_datastream

data_source arkivering_oppgave_datastream:
  type: bigquery
  connection:
    project_id: flex-prod-af40
    dataset: arkivering_oppgave_datastream

data_source sak_status_metrikk_datastream:
  type: bigquery
  connection:
    project_id: flex-prod-af40
    dataset: sak_status_metrikk_datastream

data_source modia_kontakt_metrikk_datastream:
  type: bigquery
  connection:
    project_id: flex-prod-af40
    dataset: modia_kontakt_metrikk_datastream

data_source flexjar_datastream:
  type: bigquery
  connection:
    project_id: flex-prod-af40
    dataset: flexjar_datastream

data_source inntektsmelding_status_datastream:
  type: bigquery
  connection:
    project_id: flex-prod-af40
    dataset: inntektsmelding_status_datastream
