name: deploy-alerts
on:
  push:
    branches:
      - main
    paths:
      - 'nais/alerts.yaml'
      - '.github/workflows/alerts.yaml'

jobs:
  apply-alerts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/alerts.yaml

