name: deploy-jobs
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.gitignore'
      - 'local/'
      - 'nais/alerts.yaml'
      - '.github/workflows/alerts.yaml'

jobs:
  deploy-prod-run-once:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/soda-config.yaml,nais/soda-checks-prod.yaml,nais/naisjob.yaml
          VARS: nais/prod-run-once.yaml

  deploy-prod-run-scheduled:
    needs: [deploy-prod-run-once]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/soda-config.yaml,nais/soda-checks-prod.yaml,nais/naisjob.yaml
          VARS: nais/prod.yaml
